"""update vehicle types

Revision ID: f41cbd01373a
Revises: b7fc66f81959
Create Date: 2026-06-01 11:48:52.230891+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f41cbd01373a'
down_revision: Union[str, None] = 'b7fc66f81959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('couriers', 'vehicle_type',
               existing_type=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'),
               type_=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', 'E_CAR', 'E_BIKE', 'COLD_CAR', name='vehicletype', native_enum=False),
               existing_nullable=False)
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'),
               type_=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', 'E_CAR', 'E_BIKE', 'COLD_CAR', name='vehicletype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'vehicle_type',
               existing_type=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', 'E_CAR', 'E_BIKE', 'COLD_CAR', name='vehicletype', native_enum=False),
               type_=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'),
               existing_nullable=False)
    op.alter_column('couriers', 'vehicle_type',
               existing_type=sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', 'E_CAR', 'E_BIKE', 'COLD_CAR', name='vehicletype', native_enum=False),
               type_=postgresql.ENUM('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'),
               existing_nullable=False)
    # ### end Alembic commands ###
