"""init all services

Revision ID: c6bf7919336f
Revises: 
Create Date: 2026-05-19 11:56:13.265285+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bf7919336f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('actions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_permission_table_name', 'permissions', ['table_name'], unique=False)
    op.create_index(op.f('ix_permissions_table_name'), 'permissions', ['table_name'], unique=True)
    op.create_index('uq_permission_table_name', 'permissions', ['table_name'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('monthly_delivery_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_product_id'),
    sa.UniqueConstraint('tier')
    )
    op.create_index('idx_plan_active', 'plans', ['is_active'], unique=False)
    op.create_index('idx_plan_tier', 'plans', ['tier'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'COURIER', 'RECIPIENT', name='roletype'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_role_name')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('plan_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.Enum('SEK', 'EUR', 'USD', 'GBP', 'NOK', 'DKK', 'OMR', 'UAD', name='currency'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_index('idx_plan_price_currency', 'plan_prices', ['currency'], unique=False)
    op.create_index('idx_plan_price_plan_currency', 'plan_prices', ['plan_id', 'currency'], unique=False)
    op.create_index('idx_plan_price_plan_id', 'plan_prices', ['plan_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index('idx_role_permission_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_permission_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DELETED', name='userstatus'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_last_login', 'users', ['last_login_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('billing_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.Enum('SEK', 'EUR', 'USD', 'GBP', 'NOK', 'DKK', 'OMR', 'UAD', name='currency'), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_billing_customer_stripe_id', 'billing_customers', ['stripe_customer_id'], unique=False)
    op.create_index('idx_billing_customer_user_id', 'billing_customers', ['user_id'], unique=False)
    op.create_table('couriers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_courier_user_id', 'couriers', ['user_id'], unique=False)
    op.create_table('password_reset_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_codes_code'), 'password_reset_codes', ['code'], unique=True)
    op.create_index(op.f('ix_password_reset_codes_is_used'), 'password_reset_codes', ['is_used'], unique=False)
    op.create_index(op.f('ix_password_reset_codes_user_id'), 'password_reset_codes', ['user_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipient_location', 'recipients', ['latitude', 'longitude'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_refresh_token_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_token_token', 'refresh_tokens', ['token'], unique=False)
    op.create_index('idx_refresh_token_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_avatars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_avatar_user_id', 'user_avatars', ['user_id'], unique=False)
    op.create_table('courier_current_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('delivered_order_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('courier_id')
    )
    op.create_index('idx_courier_current_state_courier_id', 'courier_current_states', ['courier_id'], unique=False)
    op.create_index('idx_courier_current_state_created_at', 'courier_current_states', ['created_at'], unique=False)
    op.create_index('idx_courier_current_state_state', 'courier_current_states', ['state'], unique=False)
    op.create_table('hubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('setup_time', sa.Interval(), nullable=False),
    sa.Column('service_time', sa.Interval(), nullable=False),
    sa.Column('return_to_hub', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hub_courier_id', 'hubs', ['courier_id'], unique=False)
    op.create_index('idx_hub_location', 'hubs', ['lat', 'lon'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_customer_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_price_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'INCOMPLETE', 'PAUSED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_price_id'], ['plan_prices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('idx_subscription_customer_id', 'subscriptions', ['billing_customer_id'], unique=False)
    op.create_index('idx_subscription_plan_id', 'subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_stripe_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'CAR', 'VAN', 'TRUCK', 'TRAILER', name='vehicletype'), nullable=False),
    sa.Column('weight_capacity', sa.Float(), nullable=True),
    sa.Column('volume_capacity', sa.Float(), nullable=True),
    sa.Column('loading_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('travel_cost_per_km', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('travel_cost_per_hour', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('loading_time', sa.Interval(), nullable=False),
    sa.Column('average_speed', sa.Integer(), nullable=False),
    sa.Column('max_duration', sa.Interval(), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('fuel_consumption_per_100_km', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', 'ELECTRICAL', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('max_tasks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vehicle_courier_id', 'vehicles', ['courier_id'], unique=False)
    op.create_index('idx_vehicle_type', 'vehicles', ['vehicle_type'], unique=False)
    op.create_table('hub_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('finish_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['terminal_id'], ['hubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hub_shift_terminal_id', 'hub_shifts', ['terminal_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=False),
    sa.Column('amount_due', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('SEK', 'EUR', 'USD', 'GBP', 'NOK', 'DKK', 'OMR', 'UAD', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE', name='invoicestatus'), nullable=False),
    sa.Column('invoice_pdf_url', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_index('idx_invoice_customer_id', 'invoices', ['billing_customer_id'], unique=False)
    op.create_index('idx_invoice_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoice_stripe_id', 'invoices', ['stripe_invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('SEK', 'EUR', 'USD', 'GBP', 'NOK', 'DKK', 'OMR', 'UAD', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index('idx_payment_customer_id', 'payments', ['billing_customer_id'], unique=False)
    op.create_index('idx_payment_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payment_stripe_id', 'payments', ['stripe_payment_intent_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('billing_customer_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('delivery_limit', sa.Integer(), nullable=False),
    sa.Column('overage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_customer_id', 'usage_records', ['billing_customer_id'], unique=False)
    op.create_index('idx_usage_period', 'usage_records', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_usage_subscription_id', 'usage_records', ['subscription_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'SCHEDULED', 'DELIVERED', 'CANCELLED', 'POSTPONED', 'UNASSIGNED', name='orderstatustypes'), nullable=False),
    sa.Column('geo_location_provided', sa.Boolean(), nullable=True),
    sa.Column('time_window_earliest', sa.Time(), nullable=True),
    sa.Column('time_window_latest', sa.Time(), nullable=True),
    sa.Column('weight_occupation', sa.Float(), nullable=False),
    sa.Column('volume_occupation', sa.Float(), nullable=False),
    sa.Column('is_return', sa.Boolean(), nullable=False),
    sa.Column('original_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('moved_as', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['hub_shifts.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_barcode', 'orders', ['barcode'], unique=False)
    op.create_index('idx_order_courier_id', 'orders', ['courier_id'], unique=False)
    op.create_index('idx_order_courier_status', 'orders', ['courier_id', 'status'], unique=False)
    op.create_index('idx_order_expected_delivery', 'orders', ['expected_delivery_date'], unique=False)
    op.create_index('idx_order_hub_status', 'orders', ['terminal_id', 'status'], unique=False)
    op.create_index('idx_order_is_return', 'orders', ['is_return'], unique=False)
    op.create_index('idx_order_recipient_id', 'orders', ['recipient_id'], unique=False)
    op.create_index('idx_order_recipient_status', 'orders', ['recipient_id', 'status'], unique=False)
    op.create_index('idx_order_shift_id', 'orders', ['shift_id'], unique=False)
    op.create_index('idx_order_shift_status', 'orders', ['shift_id', 'status'], unique=False)
    op.create_index('idx_order_status', 'orders', ['status'], unique=False)
    op.create_index('idx_order_terminal_id', 'orders', ['terminal_id'], unique=False)
    op.create_index('idx_order_time_window', 'orders', ['time_window_earliest', 'time_window_latest'], unique=False)
    op.create_index(op.f('ix_orders_barcode'), 'orders', ['barcode'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('finish_time', sa.Time(), nullable=False),
    sa.Column('actual_start_time', sa.Time(), nullable=True),
    sa.Column('actual_finish_time', sa.Time(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('current_mission_id', sa.UUID(), nullable=True),
    sa.Column('must_return', sa.Boolean(), nullable=False),
    sa.Column('number_of_missions', sa.Integer(), nullable=False),
    sa.Column('total_waiting_time', sa.Integer(), nullable=True),
    sa.Column('total_actual_waiting_time', sa.Integer(), nullable=True),
    sa.Column('total_number_of_orders', sa.Integer(), nullable=True),
    sa.Column('total_number_of_stops', sa.Integer(), nullable=True),
    sa.Column('loading_time_start', sa.DateTime(), nullable=True),
    sa.Column('arrived_at_hub_time', sa.DateTime(), nullable=True),
    sa.Column('lock', sa.Boolean(), nullable=True),
    sa.Column('created_type', sa.String(length=50), nullable=True),
    sa.Column('modification_time', sa.Time(), nullable=True),
    sa.Column('courier_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['hub_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['hubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_route_courier_id', 'routes', ['courier_id'], unique=False)
    op.create_index('idx_route_shift_id', 'routes', ['shift_id'], unique=False)
    op.create_index('idx_route_status', 'routes', ['status'], unique=False)
    op.create_index('idx_route_terminal_id', 'routes', ['terminal_id'], unique=False)
    op.create_index('idx_route_vehicle_id', 'routes', ['vehicle_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('terminal_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('is_return', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('cumulative_duration', sa.Integer(), nullable=True),
    sa.Column('cumulative_distance', sa.Integer(), nullable=True),
    sa.Column('service_time', sa.Integer(), nullable=True),
    sa.Column('actual_arrival_time', sa.Time(), nullable=True),
    sa.Column('actual_cumulative_duration', sa.Integer(), nullable=True),
    sa.Column('actual_cumulative_distance', sa.Integer(), nullable=True),
    sa.Column('actual_service_time', sa.Integer(), nullable=True),
    sa.Column('actual_mission_start_time', sa.Time(), nullable=True),
    sa.Column('actual_mission_finish_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('postponed', sa.String(length=50), nullable=True),
    sa.Column('position_in_route', sa.Integer(), nullable=True),
    sa.Column('waiting_time', sa.Integer(), nullable=True),
    sa.Column('actual_waiting_time', sa.Integer(), nullable=True),
    sa.Column('loading_scan_parcel_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_scan_parcel_time', sa.DateTime(), nullable=True),
    sa.Column('delivery_scan_parcel_barcode', sa.String(length=255), nullable=True),
    sa.Column('courier_comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['hub_shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_id'], ['hubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_mission_courier_id', 'missions', ['courier_id'], unique=False)
    op.create_index('idx_mission_order_id', 'missions', ['order_id'], unique=False)
    op.create_index('idx_mission_position', 'missions', ['route_id', 'position_in_route'], unique=False)
    op.create_index('idx_mission_route_id', 'missions', ['route_id'], unique=False)
    op.create_index('idx_mission_status', 'missions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mission_status', table_name='missions')
    op.drop_index('idx_mission_route_id', table_name='missions')
    op.drop_index('idx_mission_position', table_name='missions')
    op.drop_index('idx_mission_order_id', table_name='missions')
    op.drop_index('idx_mission_courier_id', table_name='missions')
    op.drop_table('missions')
    op.drop_index('idx_route_vehicle_id', table_name='routes')
    op.drop_index('idx_route_terminal_id', table_name='routes')
    op.drop_index('idx_route_status', table_name='routes')
    op.drop_index('idx_route_shift_id', table_name='routes')
    op.drop_index('idx_route_courier_id', table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_barcode'), table_name='orders')
    op.drop_index('idx_order_time_window', table_name='orders')
    op.drop_index('idx_order_terminal_id', table_name='orders')
    op.drop_index('idx_order_status', table_name='orders')
    op.drop_index('idx_order_shift_status', table_name='orders')
    op.drop_index('idx_order_shift_id', table_name='orders')
    op.drop_index('idx_order_recipient_status', table_name='orders')
    op.drop_index('idx_order_recipient_id', table_name='orders')
    op.drop_index('idx_order_is_return', table_name='orders')
    op.drop_index('idx_order_hub_status', table_name='orders')
    op.drop_index('idx_order_expected_delivery', table_name='orders')
    op.drop_index('idx_order_courier_status', table_name='orders')
    op.drop_index('idx_order_courier_id', table_name='orders')
    op.drop_index('idx_order_barcode', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_usage_subscription_id', table_name='usage_records')
    op.drop_index('idx_usage_period', table_name='usage_records')
    op.drop_index('idx_usage_customer_id', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('idx_payment_stripe_id', table_name='payments')
    op.drop_index('idx_payment_status', table_name='payments')
    op.drop_index('idx_payment_customer_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_invoice_stripe_id', table_name='invoices')
    op.drop_index('idx_invoice_status', table_name='invoices')
    op.drop_index('idx_invoice_customer_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_hub_shift_terminal_id', table_name='hub_shifts')
    op.drop_table('hub_shifts')
    op.drop_index('idx_vehicle_type', table_name='vehicles')
    op.drop_index('idx_vehicle_courier_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('idx_subscription_stripe_id', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_plan_id', table_name='subscriptions')
    op.drop_index('idx_subscription_customer_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_hub_location', table_name='hubs')
    op.drop_index('idx_hub_courier_id', table_name='hubs')
    op.drop_table('hubs')
    op.drop_index('idx_courier_current_state_state', table_name='courier_current_states')
    op.drop_index('idx_courier_current_state_created_at', table_name='courier_current_states')
    op.drop_index('idx_courier_current_state_courier_id', table_name='courier_current_states')
    op.drop_table('courier_current_states')
    op.drop_index('idx_user_avatar_user_id', table_name='user_avatars')
    op.drop_table('user_avatars')
    op.drop_index('idx_refresh_token_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_token', table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_recipient_location', table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_password_reset_codes_user_id'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_is_used'), table_name='password_reset_codes')
    op.drop_index(op.f('ix_password_reset_codes_code'), table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    op.drop_index('idx_courier_user_id', table_name='couriers')
    op.drop_table('couriers')
    op.drop_index('idx_billing_customer_user_id', table_name='billing_customers')
    op.drop_index('idx_billing_customer_stripe_id', table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_last_login', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_role_permission_role_id', table_name='role_permissions')
    op.drop_index('idx_role_permission_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_plan_price_plan_id', table_name='plan_prices')
    op.drop_index('idx_plan_price_plan_currency', table_name='plan_prices')
    op.drop_index('idx_plan_price_currency', table_name='plan_prices')
    op.drop_table('plan_prices')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_plan_tier', table_name='plans')
    op.drop_index('idx_plan_active', table_name='plans')
    op.drop_table('plans')
    op.drop_index('uq_permission_table_name', table_name='permissions')
    op.drop_index(op.f('ix_permissions_table_name'), table_name='permissions')
    op.drop_index('idx_permission_table_name', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
