"""terminal and courier setup

Revision ID: 8eb87bca458d
Revises: 2b6d05dc2a47
Create Date: 2026-06-08 08:46:21.490769+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8eb87bca458d"
down_revision: Union[str, None] = "2b6d05dc2a47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_terminal_setup_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_courier_profile_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_courier_profile_completed")
    op.drop_column("users", "is_terminal_setup_completed")
    # ### end Alembic commands ###
